In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply

In [24]:
data = pd.read_csv('CarPrice.csv')

In [25]:
data

car_ID  symboling  wheelbase  carlength  carwidth  carheight  curbweight  \
0         1          3       88.6      168.8      64.1       48.8        2548   
1         2          3       88.6      168.8      64.1       48.8        2548   
2         3          1       94.5      171.2      65.5       52.4        2823   
3         4          2       99.8      176.6      66.2       54.3        2337   
4         5          2       99.4      176.6      66.4       54.3        2824   
..      ...        ...        ...        ...       ...        ...         ...   
200     201         -1      109.1      188.8      68.9       55.5        2952   
201     202         -1      109.1      188.8      68.8       55.5        3049   
202     203         -1      109.1      188.8      68.9       55.5        3012   
203     204         -1      109.1      188.8      68.9       55.5        3217   
204     205         -1      109.1      188.8      68.9       55.5        3062   

     enginesize  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0           130       3.47    2.68               9.0         111     5000   
1           130       3.47    2.68               9.0         111     5000   
2           152       2.68    3.47               9.0         154     5000   
3           109       3.19    3.40              10.0         102     5500   
4           136       3.19    3.40               8.0         115     5500   
..          ...        ...     ...               ...         ...      ...   
200         141       3.78    3.15               9.5         114     5400   
201         141       3.78    3.15               8.7         160     5300   
202         173       3.58    2.87               8.8         134     5500   
203         145       3.01    3.40              23.0         106     4800   
204         141       3.78    3.15               9.5         114     5400   

     citympg  highwaympg    price  
0         21          27  13495.0  
1         21          27  16500.0  
2         19          26  16500.0  
3         24          30  13950.0  
4         18          22  17450.0  
..       ...         ...      ...  
200       23          28  16845.0  
201       19          25  19045.0  
202       18          23  21485.0  
203       26          27  22470.0  
204       19          25  22625.0  

[205 rows x 16 columns]

In [34]:
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

In [35]:
x.shape

(205, 14)

In [36]:
y.shape

(205,)

In [31]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8,test_size = 0.2,random_state = 100)

In [38]:
x_train

array([[ 2.000e+00,  9.980e+01,  1.766e+02, ...,  5.500e+03,  2.400e+01,
         3.000e+01],
       [ 0.000e+00,  9.570e+01,  1.663e+02, ...,  4.800e+03,  3.000e+01,
         3.700e+01],
       [ 3.000e+00,  9.630e+01,  1.730e+02, ...,  5.000e+03,  2.500e+01,
         3.200e+01],
       ...,
       [-1.000e+00,  1.100e+02,  1.909e+02, ...,  4.350e+03,  2.200e+01,
         2.500e+01],
       [ 1.000e+00,  9.370e+01,  1.573e+02, ...,  5.500e+03,  3.100e+01,
         3.800e+01],
       [ 1.000e+00,  1.058e+02,  1.927e+02, ...,  5.500e+03,  1.700e+01,
         2.000e+01]])

In [39]:
y_train

array([13950.   ,  7198.   ,  8499.   ,  5399.   ,  8949.   ,  7609.   ,
        9279.   ,  7995.   ,  9495.   ,  6795.   ,  9639.   ,  8238.   ,
        9995.   , 18920.   ,  7898.   ,  8921.   ,  8921.   , 12964.   ,
        7775.   , 10295.   , 37028.   ,  7609.   , 22018.   ,  9538.   ,
       16500.   , 18950.   ,  9980.   ,  7499.   , 11248.   , 15750.   ,
        7999.   ,  6229.   , 18150.   , 13645.   ,  8916.5  ,  6918.   ,
        6989.   , 34028.   ,  6338.   , 22625.   , 16430.   ,  6575.   ,
       11199.   , 12629.   , 20970.   , 41315.   , 16558.   ,  7099.   ,
        5499.   ,  8916.5  ,  8358.   , 17950.   , 11595.   , 13845.   ,
        8013.   ,  6095.   ,  9988.   ,  8845.   ,  8058.   ,  7895.   ,
       17710.   ,  7395.   ,  6692.   ,  5572.   , 35550.   , 17859.167,
        7957.   ,  7295.   , 16900.   ,  5195.   , 10245.   , 11259.   ,
        7463.   ,  6295.   , 12940.   , 10945.   ,  7775.   ,  6377.   ,
       10345.   , 14399.   ,  8195.   ,  6529.   , 

In [40]:
from sklearn.linear_model import LinearRegression

In [42]:
LR = LinearRegression()

In [50]:
LR.fit(x_train,y_train)
print(LR.score(x_test,y_test))

0.8632404229751887


In [54]:
y_pred = LR.predict(x_test)
y_pred

array([ 6345.51521043, 10444.16409554, 10116.30814663, 11778.38180243,
        9381.5019242 , 10136.19388545, 16268.52536737, 18937.42321919,
       15161.94719869, 23060.5629997 , 17626.04937298, 17585.76020857,
       18335.49560768, 10470.45980788, 39044.52405616,  7815.16517026,
        6584.50277513, 14523.57566783, 15763.62153262, 16101.6033964 ,
       16877.71369056, 16692.27219361, 26532.77602706,  5713.99078284,
       13548.95352988, 22121.75641053, 15761.35565731, 24185.72335841,
       12595.6517244 , 11666.09754637,  7557.98273462, 26211.97538945,
       18746.10896534, 19450.86431538, 15268.90770831, 11372.05726556,
       19530.96706899, 13585.29066706,  6288.20872014,  8211.86266878,
       37992.05168056])

In [57]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [83]:
r_squared = r2_score(y_test,y_pred)
r_squared

0.8632404229751887

NameError: name 'ypred_train' is not defined

In [84]:
from sklearn.model_selection import KFold, cross_val_score
kf = KFold(shuffle = True, random_state = 80)
cross_scores = cross_val_score(LR, x_test, y_test, cv=kf)
kf_test = np.sqrt(np.mean(np.abs(cross_scores)))
print(kf_test)

0.7055659243475305


In [82]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha = 1)
ridge.fit(x_train, y_train)
ridge.score(x_test, y_test)
cross_scores2 = cross_val_score(ridge, x_test, y_test, cv = kf)
reg_test = np.sqrt(np.mean(np.abs(cross_scores2)))
print(reg_test)

0.7670901183457489
